# Generated by Django 4.2.5 on 2023-11-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_about_signup_delete_singup_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ck', 'Cakes'), ('pr', 'PuranPoli'), ('pd', 'Papad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='signup',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
